import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { data } from "../data";
import Link from "next/link";
export default function Home() {
  console.log("data", data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="section">
        <h1>{data.name}</h1>
        <h3>{data.location}</h3>
        <section className={styles.grid}>
          {data &&
            data.categories.map((category, i) => (
              <div className={styles.gridItem} key={i}>
                <h4 className={styles.categories}>{category.category}</h4>
                <div className={`${styles.main} ${styles.pic}`}>
                  {category.pictures.map((picture, ind) => (
                    <Link href={`/categories/${category.category}`} key={ind}>
                      <span>
                        <Image
                          src={picture.img}
                          width={300}
                          height={300}
                          key={ind}
                          alt={picture.img}
                        />
                        <p className={styles.pictureDate}>{picture.date}</p>
                      </span>
                    </Link>
                  ))}
                </div>
              </div>
            ))}
        </section>
      </main>
    </div>
  );
}
