import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import DatePicker, { registerLocale } from "react-datepicker";
import sv from "date-fns/locale/sv"; // the locale you want
registerLocale("sv", sv);
import { createClient } from "@supabase/supabase-js";
import { Controller, useForm } from "react-hook-form";
import "react-datepicker/dist/react-datepicker.css";
const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY
);

export default function Home({ images }) {
  const { register, handleSubmit, reset, watch, control } = useForm();
  const onSubmit = async (post) => {
    try {
      await supabaseAdmin.storage
        .from("gallery")
        .upload(
          `${post.category}/${post.categoryChild}/${post.file[0].name}`,
          post.file[0]
        );

      await supabaseAdmin.from("GalleryTable").insert([
        {
          category: post.category,
          categoryChild: post.categoryChild,
          img: post.file[0].name,
          date: watch("dateInput")?.toLocaleString("sv-SE").substr(0, 10),
        },
      ]);

      reset();
    } catch (err) {}
  };
  // useEffect(() => {
  //   const fetchData = async () => {
  //     const response = await fetch("/api/categories/categories");
  //     const json = await response.json();
  //     setCategories(json);
  //   };
  //   fetchData();
  // }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="section">
        <form onSubmit={handleSubmit(onSubmit)} className={styles.form}>
          <label>Kategori</label>
          <input {...register("category", { required: true, maxLength: 20 })} />
          <label>Kategori Child</label>
          <input {...register("categoryChild", { pattern: /^[A-Za-z]+$/i })} />
          <label>Välj bild</label>
          <input {...register("file")} type="file" />
          <label>Välj Datum</label>
          <Controller
            control={control}
            name="dateInput"
            render={({ field }) => (
              <DatePicker
                locale="sv"
                placeholderText="Välj datum"
                onChange={(date) => field.onChange(date)}
                selected={field.value}
              />
            )}
          />

          <button type="submit">Skicka</button>
        </form>

        <h1>Markus Wiland</h1>
        <h3>Location</h3>
        <section className={styles.grid}>
          {images
            .map((o) => o.category)
            .filter((o, i, self) => self.indexOf(o) === i)
            .map((category, i) => (
              <div className={styles.gridItem} key={i}>
                <h2>{category}</h2>
                <div className={`${styles.pic}`}>
                  {images.map((o, i) => {
                    if (o.category === category) {
                      return (
                        <Link href={`/categories/${o.category}`} key={o.id}>
                          <span>
                            <Image
                              src={`https://wkvxfukoitljukptneli.supabase.co/storage/v1/object/public/gallery/${o.category}/${o.categoryChild}/${o.img}`}
                              width={300}
                              height={300}
                              alt={o.img}
                            />
                            <p className={styles.pictureDate}>{o.date}</p>
                          </span>
                        </Link>
                      );
                    }
                  })}
                </div>
              </div>
            ))}
          {/* {categories &&
            categories.categories?.map((category, i) => (
              <div className={styles.gridItem} key={i}>
                <h4 className={styles.categories}>{category.category}</h4>
                <div className={`${styles.main} ${styles.pic}`}>
                
                  {category.pictures.map((picture) =>
                    picture.images.map((picture, ind) => (
                      <Link href={`/categories/${category.category}`} key={ind}>
                        <span>
                          <Image
                            src={picture.img}
                            width={300}
                            height={300}
                            key={ind}
                            alt={picture.img}
                          />
                          <p className={styles.pictureDate}>{picture.date}</p>
                        </span>
                      </Link>
                    ))
                  )} 
                </div>
              </div>
            ))} */}
        </section>
      </main>
    </div>
  );
}
export async function getStaticProps() {
  const { data, error } = await supabaseAdmin.from("GalleryTable").select("*");

  return {
    props: {
      images: data,
    },
  };
}
// export async function getStaticProps() {
//   const results = await fetch(
//     `https://api.cloudinary.com/v1_1/${process.env.CLOUDINARY_CLOUD_NAME}/resources/image`,
//     {
//       headers: {
//         Authorization: `Basic ${Buffer.from(
//           process.env.CLOUDINARY_API_KEY +
//             ":" +
//             process.env.CLOUDINARY_API_SECRET
//         ).toString("base64")}`,
//       },
//     }
//   ).then((r) => r.json());

//   const { resources } = results;
//   const images = resources.map((resource) => {
//     return {
//       img: resource.secure_url,
//       url: resource.url,
//       width: resource.width,
//       height: resource.height,
//       id: resource.asset_id,
//       title: resource.public_id,
//       date: resource.created_at,
//     };
//   });
//   console.log("results", results);
//   return {
//     props: {
//       images,
//     },
//   };
// }
